### ISSUE TITLE
Add safari support or at least exception to indicate we are lacking it

### ISSUE THREAD

**Issue by other019** [devonfw-forge/mrchecker-source#31]
https://github.com/devonfw-forge/mrchecker-source/blob/f78e3b30cc95dfa26229c8706dda83e1bd242080/mrchecker-framework-modules/mrchecker-selenium-module/src/main/java/com/capgemini/mrchecker/selenium/core/newDrivers/DriverManager.java#L405

**Comment by KMariusz** [comment]
Removed SAFARI from DriverManager.
Exception will be thrown when trying to use unsupported browser
